# Generated by Django 4.0.3 on 2022-04-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=5)),
                ('off', models.FloatField(default=0.0)),
                ('purpose', models.CharField(max_length=255)),
            ],
        ),
    ]
