# Generated by Django 4.0.3 on 2022-04-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_discount_prdt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='prdt',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='products.discount'),
        ),
    ]
